"""Turns raw breach events into a professional Incident Report (PDF).

Two jobs:
  classify()         -> threat level + plain-English data-exposure estimate
  build_report_pdf() -> a one-click forensic report grouped by attacker

Because the decoy data is generated, we know exactly what was in each file the
attacker took, so the exposure estimates are concrete (not hand-wavy).
"""

from datetime import datetime

TIME_FMT = "%Y-%m-%d %H:%M:%S UTC"
SEV_RANK = {"CRITICAL": 3, "HIGH": 2, "MEDIUM": 1, "LOW": 0}


def classify(detail, kind):
    """Return (severity, exposure_text) for one breach event."""
    d = (detail or "").lower()
    if "login_attempt" in d:
        return ("CRITICAL", "Captured the username an intruder typed into the fake portal")
    if any(k in d for k in ("login", "password", "cred")):
        return ("CRITICAL", "System logins & passwords (5 credentials)")
    if "bank" in d:
        return ("CRITICAL", "Banking records & transactions")
    if "tax" in d:
        return ("HIGH", "Tax return / financial records")
    if "payroll" in d:
        return ("HIGH", "~6 employee records (salaries, emails, bank accounts)")
    if "customer" in d:
        return ("HIGH", "~10 customer records (names, emails, phones)")
    if kind == "file":
        return ("HIGH", "Confidential file contents")
    if kind == "login":
        return ("MEDIUM", "Attempted to use the fake internal login")
    if kind == "portal":
        return ("MEDIUM", "Browsed the internal document portal")
    if kind == "link":
        return ("LOW", "Tracking link / pixel was opened")
    return ("MEDIUM", "A decoy was accessed")


def _dt(s):
    try:
        return datetime.strptime(s, TIME_FMT)
    except Exception:
        return None


def _dwell(events):
    """Seconds between the attacker's first and last action."""
    times = [t for t in (_dt(e.get("triggered_at", "")) for e in events) if t]
    if len(times) < 2:
        return 0
    return int((max(times) - min(times)).total_seconds())


def _human(sec):
    if sec < 60:
        return f"{sec} sec"
    if sec < 3600:
        return f"{sec // 60} min"
    return f"{sec // 3600} hr"


def _latin1(s):
    """fpdf core fonts are latin-1 only; drop anything they can't encode."""
    return (str(s) or "").encode("latin-1", "replace").decode("latin-1")


def _wrap(pdf, text, h=5):
    """multi_cell that always resets to the left margin and breaks long tokens.

    fpdf2's multi_cell otherwise leaves the cursor at the right edge, so the
    next call gets ~zero width and crashes ('not enough horizontal space')."""
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(pdf.epw, h, text, new_x="LMARGIN", new_y="NEXT", wrapmode="CHAR")


def summarize(events):
    """High-level numbers for the report header and the dashboard."""
    if not events:
        return {"breaches": 0, "attackers": 0, "top_severity": "NONE"}
    sevs = [classify(e.get("detail", ""), e.get("token_kind", ""))[0] for e in events]
    top = max(sevs, key=lambda s: SEV_RANK[s])
    return {
        "breaches": len(events),
        "attackers": len({e.get("ip") for e in events}),
        "top_severity": top,
    }


def build_report_pdf(events):
    """Build the incident report PDF (bytes). `events` newest-first is fine."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ---- header ----
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "SECURITY INCIDENT REPORT", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(110, 110, 110)
    pdf.cell(0, 6, _latin1("Generated by Canary - Deception Network  |  "
                           + datetime.utcnow().strftime(TIME_FMT)),
             new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    s = summarize(events)
    if not events:
        pdf.set_font("Helvetica", "", 12)
        pdf.cell(0, 8, "No breaches recorded. All decoys are quiet.",
                 new_x="LMARGIN", new_y="NEXT")
        return bytes(pdf.output())

    # ---- executive summary ----
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Executive Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    _wrap(pdf, _latin1(
        f"{s['breaches']} breach event(s) were detected from {s['attackers']} "
        f"distinct source(s). Highest threat level: {s['top_severity']}. "
        f"Decoys are never touched by legitimate staff, so each event below "
        f"indicates unauthorized access. Industry average time to even detect a "
        f"breach is 204 days; these were detected instantly."))
    pdf.ln(3)

    # ---- group by attacker IP ----
    groups = {}
    for e in events:
        groups.setdefault(e.get("ip", "unknown"), []).append(e)

    for ip, evs in groups.items():
        evs_sorted = sorted(evs, key=lambda e: e.get("triggered_at", ""))
        geo = evs_sorted[0].get("geo", "Unknown")
        ua = evs_sorted[0].get("user_agent", "unknown")
        grp_sev = max(
            (classify(e.get("detail", ""), e.get("token_kind", ""))[0] for e in evs),
            key=lambda x: SEV_RANK[x])

        pdf.ln(2)
        pdf.set_draw_color(220, 220, 220)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, _latin1(f"Attacker: {ip}   [{grp_sev}]"),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(90, 90, 90)
        _wrap(pdf, _latin1(
            f"Location/ISP: {geo}\n"
            f"Device: {ua}\n"
            f"Activity window: {_human(_dwell(evs_sorted))} "
            f"({len(evs_sorted)} action(s))"))
        pdf.set_text_color(0, 0, 0)
        pdf.ln(1)

        # timeline of actions
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Timeline & data exposure:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        for e in evs_sorted:
            sev, exposure = classify(e.get("detail", ""), e.get("token_kind", ""))
            took = e.get("detail") or e.get("token_name") or "decoy"
            line = f"- {e.get('triggered_at','')}  [{sev}]  {took}  ->  {exposure}"
            _wrap(pdf, _latin1(line))
        pdf.ln(1)

    # ---- recommended actions ----
    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Recommended Actions", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    for i, step in enumerate([
        "Reset all admin, email, and banking passwords immediately.",
        "Disconnect affected machines from the network.",
        "Preserve logs and this report for your insurer / IT provider.",
        "Review accounts for the data types exposed above.",
    ], 1):
        _wrap(pdf, _latin1(f"{i}. {step}"), h=6)

    return bytes(pdf.output())
